spring:
  zipkin:
    baseUrl: ${TRACE_SERVICE_URI}  
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URI}
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0    
logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-},%X{mybaggage:-}]"            
info:
  app:
    name: Dev Store Gateway
    description: This is gateway service for Dev Store
  company:
    name: Cross Training
    department: IT
---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/customer/**
        - id: catalog
          uri: lb://catalog
          predicates:
            - Path=/catalog/**
        - id: rating
          uri: lb://rating
          predicates:
            - Path=/rating/**
        - id: recommendation
          uri: lb://recommendation
          predicates:
            - Path=/recommendation/**
        - id: shipping
          uri: lb://shipping
          predicates:
            - Path=/shipping/**
        - id: transaction
          uri: lb://transaction
          predicates:
            - Path=/transaction/**            
