spring:
  application:
    name: catalog
  profiles:
    active: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: catalog
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/
server:
  port: 9001
info:
  app:
    name: Dev Store Catalog
    description: This is catalog service for Dev Store
    version: 1.0.0
  company:
    name: Cross Training
    department: IT