spring:
  zipkin:
    baseUrl: ${TRACE_SERVICE_URI}   
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    schema: ${DB_SCHEMA}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: catalog
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URI}
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true 
info:
  app:
    name: Dev Store Catalog
    description: This is catalog service for Dev Store
    version: ${VERSION}
  company:
    name: Cross Training
    department: IT
