spring:
  application:
    name: discovery
  zipkin:
    baseUrl: ${LOGGING_SERVICE_URI} 
server:
  port: ${PORT:8080}
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
info:
  app:
    name: Dev Store Discovery
    description: This is discovery service for Dev Store
    version: 1.0.0
  company:
    name: Cross Training
    department: IT