spring:
  application:
    name: gateway
server:
  port: 9100
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/  
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
