spring:
  application:
    name: rating
  profiles:
    active: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: rating
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  app:
    name: Dev Store Rating
    description: This is rating service for Dev Store
    version: 1.0.0
  company:
    name: Cross Training
    department: IT