spring:
  zipkin:
    baseUrl: ${TRACE_SERVICE_URI}  
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URI}
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true 
info:
  app:
    name: Dev Store Transaction Reception
    description: This is transaction reception service for Dev Store
  company:
    name: Cross Training
    department: IT 
